name: Docker Build and Push

on:
  push:
    branches:
      - deployment

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Docker Buildx for multi-platform builds
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to GitHub Container Registry (GHCR)
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push backend image
      - name: Build and push backend Docker image
        run: |
          docker build -f Dockerfile.backend -t ghcr.io/${{ github.repository }}/backend:latest .
          docker push ghcr.io/${{ github.repository }}/backend:latest

      # Build and push frontend image
      - name: Build and push frontend Docker image
        run: |
          docker build -f Dockerfile.frontend -t ghcr.io/${{ github.repository }}/frontend:latest .
          docker push ghcr.io/${{ github.repository }}/frontend:latest
